default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/rails_calendar_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/rails_calendar_test") %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_CACHE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DATABASE_QUEUE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_CABLE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
